sudo: required

language: php
  - 7.0
services:
  - docker

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - docker-compose up -d db

install:
  - docker-compose run php composer install

script:
  - docker-compose run php vendor/bin/codecept run
  - docker-compose run php-patched vendor/bin/codecept run